apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: xdew-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
parameters:
  backupTargetName: default
  dataEngine: v1
  dataLocality: disabled
  disableRevisionCounter: "true"
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  unmapMarkSnapChainRemoved: ignored
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
