apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      name: api-docs
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2