apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api
rules:
  - apiGroups: ["xdew.ch"]
    resources: ["projects", "workspaces"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes/status"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["cloudflare-operator.io"]
    resources: ["dnsrecords", "zones"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
