apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Keycloak
      name: keycloak
    patch: |-
      - op: replace
        path: /spec/instances
        value: 1