apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edp-keycloak-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloaks
  - keycloakclients
  - keycloakrealms
  - keycloakrealmgroups
  - keycloakrealmroles
  - keycloakrealmusers
  - keycloakclientscopes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloaks/status
  - keycloakclients/status
  - keycloakrealms/status
  - keycloakrealmgroups/status
  - keycloakrealmroles/status
  - keycloakrealmusers/status
  - keycloakclientscopes/status
  verbs:
  - get
  - patch
  - update