apiVersion: apps/v1
kind: Deployment
metadata:
  name: edp-keycloak-operator
  labels:
    app: edp-keycloak-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edp-keycloak-operator
  template:
    metadata:
      labels:
        app: edp-keycloak-operator
    spec:
      serviceAccountName: edp-keycloak-operator
      containers:
      - name: keycloak-operator
        image: epamedp/keycloak-operator:v1.20.0
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "edp-keycloak-operator"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"